name: cryptotracker
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  http:
  shared_preferences:
  google_fonts:
  draggable_scrollbar:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
   - family: Delius
     fonts:
       - asset: assets/google_fonts/Delius-Regular.ttf
   - family: RockSalt
     fonts:
       - asset: assets/google_fonts/RockSalt-Regular.ttf
   - family: ArchitectsDaughter
     fonts:
       - asset: assets/google_fonts/ArchitectsDaughter-Regular.ttf